### PR TITLE
Rethrow the compilation error after printing the message.

### LINKED ISSUE #314: Compilation errors are not handled properly
I was running `grunt-contrib-watch` with `grunt-contrib-less` and other tasks, and I noticed that only `grunt-contrib-less` was behaving strangely: if a compilation error was encountered, everything just hung up.

After long search through `grount-contrib-watch` and `grunt` I am fairly certain that the problem lies with how `grunt-contrib-less` handles compilation errors.

So in the `less` task there is a `compileLess` function, which contains this code at the end:

``` js
return less.render(srcCode, options)
  .catch(function(err) {
    lessError(err, srcFile);
  });
```

As you can see, in case of an error a message is printed, and then - because nothing is returned from the function in `catch`, the promise is fulfilled with `undefined`.

The next step is this then:

``` js
compileLess(file, destFile, options)
  .then(function(output) {
    compiled.push(output.css);
    ...
```

But it should be obvious by now that this throws an error, because `output` is `undefined` (`compileLess` was fulfilled with it) and we can't get the `css` property of `undefined`.

Because there are no further error handlers, the error is just sent into nothingness and the `nextFileObj` function is not called. This seems like something that is not desired.

I'm not sure what's the appropriate fix here. Would rethrowing the error be ok?

``` js
  .catch(function(err) {
    lessError(err, srcFile);
    throw err;
  });
```

### PR DESCRIPTION
**Pull request by fatfisz**
Fixes #314 

I wanted to sign the CLA, but I don't know what would The Dojo Foundation need my address for :confused: Is there any other way in which we can move forward?

### CODE REVIEW

**Comment by fatfisz** [comment]
I wanted to sign the CLA, but I don't know what would The Dojo Foundation need my address for :confused: Is there any other way in which we can move forward?

**Comment by XhmikosR** [comment]
Shouldn't we use `grunt.log` instead of throw?

Also, can you add a test case?

**Comment by fatfisz** [comment]
Sorry, forgot to respond.

If we only `grunt.log` error, the `compiled.push(output.css);` line will still throw. I think that rethrowing in this case and passing the error to the rejection handler (`function(err) { nextFileObj(err); }`) is the best option.

About the logging thing, doesn't `less` itself log something? I don't remember rn, will check tomorrow.

About the test case: I will add it soon.

**Comment by fatfisz** [comment]
I've checked what's happening with the logs and `lessError(err, srcFile)` already takes care of that.

So the error is logged, the problem is with the swallowed exception.

**Comment by fatfisz** [comment]
I've added a test, but it requires a bit of an explanation, I guess.

Because the whole task code is kept in one file, unit testing is impossible. Therefore for the test I've decided to rely on the `fail.report` Grunt method that prints either `Done, but with warnings.` or `Done.`. When control is not returned to Grunt, this method is not called and so the `Done` word is never printed (which is what happens now).

Also the `--force` flag needs to be passed in the test because otherwise `grunt.fail.warn` in `lessError` will cause an abrupt stop and make testing impossible.

**Comment by XhmikosR** [comment]
Can't you just specify force for this one specific task in Gruntfile?

**Comment by fatfisz** [comment]
I don't understand? It's already specified in the test.

**Comment by XhmikosR** [comment]
Without going to all this trouble and doing all kind of hacks like renaming the task, which is something I certainly don't like myself.

**Comment by fatfisz** [comment]
Oh, about that - I wanted to exclude the erroring task from the rest of the batch. If you are not convinced, I could use the force indeed.

**Comment by XhmikosR** [comment]
I think it will be cleaner; just force that one specific task.

**Comment by fatfisz** [comment]
Ok, will do that in a few hours or so (I'm still at work).

**Comment by fatfisz** [comment]
I got lost; how can I force only one task? https://github.com/gruntjs/grunt/issues/810 is still open, only workarounds exist and not a built-in solution. Wat do?

**Comment by XhmikosR** [comment]
@fatfisz: did you try passing `force: true` in the specific subtask's options?

**Comment by fatfisz** [comment]
Tried it, not working.
image

**Comment by fatfisz** [comment]
(also tried with passing `force: true` not in the `options` property, but directly, with the same result)

**Pull request merged**
